config/routes.rb
Rails.application.routes.draw do
  get 'ui(/:action)', controller: 'ui'
  root 'heros#index'
  get 'join', to: 'users#new'
  post 'join', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources 'heros', only: [:show] do 
    collection do  
      get 'search', to: 'heros#search'
    end

    member do
      get 'follow', to: 'heros#follow'
      get 'unfollow', to: 'heros#unfollow'
    end
  end

  resources 'users', only: [:favs] do 
    member do 
      get 'favs', to: 'users#favs'
    end
  end
end

app/models/alias.rb
class Alias < ActiveRecord::Base
  belongs_to :hero
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :heros, ->{ order(:name) }
  validates :name, uniqueness: true
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user
  belongs_to :hero
end

app/models/hero.rb
class Hero < ActiveRecord::Base
  scope :sorted, ->{ order(:name) }
  has_many :aliases
  belongs_to :category
  has_many :relationships
  has_many :followers, through: :relationships, source: :user, dependent: :destroy
  validates_presence_of :name, :publisher, :biography

  MAX_CHARS = 240
  
  def self.search_by_name(search_term)
    return [] if search_term.blank? 
    where("name ILIKE ?", "%#{search_term}%").reverse_order
  end

  def follower?(some_user)
    followers.include?(some_user)
  end

  def summary
    summary = biography.split(".")[0..4].join(".")[0..MAX_CHARS]
    summary.concat("...") unless summary.ends_with_punctuation?
  end

  def self.select_random_heros(n = 1)
    result = []
    until result.size == n do
      hero = find(sample_heros)
      result << hero unless result.include?(hero)
    end
    result
  end

  private

  def self.sample_heros
    pluck(:id).sample
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :hero
  validates :user, presence: true
  validates :hero, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: false
  has_many :relationships
  has_many :following, through: :relationships, source: :hero, dependent: :destroy
  validates :full_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 7}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    if !logged_in?
      flash[:error] = "You have to be logged in to do that"
      redirect_to login_path and return
    end
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :require_user, only: [:follow, :unfollow]
  before_action :set_hero, only: [:show, :follow, :unfollow]

  def index
    @random_heros = Hero.select_random_heros(3)
  end

  def search
    begin
      @results = Hero.search_by_name(params[:search_term])
      flash[:notice] = "Sorry, no results for \" #{params[:search_term]}\" " if @results.empty?
    rescue NoMethodError
      flash[:error] = "Cannot search blank field ..."
      redirect_to :back
    end
  end

  def show; end

  def follow
    @hero.relationships.create!(user_id: current_user.id) unless @hero.follower?(current_user)
    flash[:notice] = "You're now following #{@hero.name}!"
    redirect_to :back
  end

  def unfollow
    @hero.relationships.find_by(user_id: current_user.id).destroy
    flash[:notice] = "You're no longer following #{@hero.name}!"
    redirect_to :back
  end

  private

  def set_hero
    @hero = Hero.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if logged_in?
  end

  def create 
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:notice] = "You are logged in"
      redirect_to root_path
    else
      flash[:error] = "There was a problem, please try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You logged out"
    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_action do  
    redirect_to :root if Rails.env.production?
  end

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash[:notice] = "Your profile was created"
      redirect_to login_path
    else
      flash[:error] = "There was a problem, please try again"
      render 'new'
    end
  end

  def favs 
    @favs = current_user.following
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/views/heros/index.html.haml
.jumbotron
  .container
    %h1 Welcome to HeroSpot!
    %p Test your knowledge of comic book heros, super villains, and video game characters.

%section.biography
  .row
    - @random_heros.each do |hero|
      = link_to hero_path(hero) do 
        .col-sm-4
          .thumbnail
            = image_tag("#{hero.small_url}", alt: "#{hero.name}")
            .caption
              %h3= "#{hero.name}" 
              %p= "#{hero.summary}"

app/views/heros/search.html.haml
.col-sm-8
  %h2= "Search Results ... search term: \" #{params[:search_term]}\""
  %hr
  = render "shared/list_heros", heros: @results
   
  

app/views/heros/show.html.haml
.jumbotron
  .container-fluid
    .row
      %div.col-sm-6(id="img_wrapper")
        = image_tag(@hero.large_url, alt: "#{@hero.name}")
      %div.col-sm-6(id="char_intro")
        = content_tag(:h1, "#{@hero.name}") 
        = link_to "#{@hero.followers.count} Followers", class: "text-info"
        %p= "#{@hero.summary}"
        - if logged_in?
          - unless @hero.follower?(current_user)
            = link_to 'Follow', follow_hero_path(@hero), class: 'btn btn-success btn-lg'
          - else 
            = link_to 'Unfollow', unfollow_hero_path(@hero), class: 'btn btn-danger btn-lg' 

%section.biography
  .col-sm-8
    %h2 Origin
    %hr
    %p= "#{@hero.biography}" 

  .panel.panel-default.info
    .panel-heading
      %h3.panel-title Information
    %ul.list-group
      %li.list-group-item
        %h4 Category
        %p= "#{@hero.category.name}"
      %li.list-group-item
        %h4 Name
        %p= "#{@hero.name}"
      %li.list-group-item
        %h4 Publisher
        %p= "#{@hero.publisher}"
      %li.list-group-item
        %h4 Alias
        - @hero.aliases.each do |another|
          %p= "#{another.name}"


    

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title HeroSpot
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    <link href='https://fonts.googleapis.com/css?family=Crete+Round' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      = render 'shared/header'
    %section.content.clearfix
      = render 'shared/messages'
      = yield

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      = link_to 'HeroSpot', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-right
      - if logged_in?
        %li
          = link_to favs_user_path(current_user) do 
            %span.glyphicon.glyphicon-star-empty
        %li= link_to 'Logout', logout_path
      - else  
        %li= link_to 'Login', login_path
        %li= link_to 'Join', join_path
    = form_tag search_heros_path, method: 'get', class: 'navbar-form navbar-right' do
      .form-group
        .input-group
          = text_field_tag :search_term, nil, class: 'form-control search-form', id: 'search_button', placeholder: 'Search for hero ...'
          %span.input-group-btn
            = button_tag class: 'btn btn-success search-btn' do
              %span.glyphicon.glyphicon-search
	  

app/views/shared/_list_heros.html.haml
- heros.each do |hero|
  .media
    .media-left.media-top
      = link_to hero_path(hero) do
        = image_tag(hero.small_url, size: "128x128", alt: "#{hero.name}", class: "media-object")
    .media-body
      %h4.media-heading= hero.name
      %p= hero.summary
  %hr

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-dismissible alert-#{name == "notice" ? "success" : "danger"}" role="alert")
    %a.close(data-dismiss="alert") &times;
    = content_tag(:strong, msg)

  

app/views/ui/hero.html.haml
.jumbotron
  .row
    %div(class="col-sm-6" id="vid_container")
      %iframe(width="560" height="315" src="https://www.youtube.com/embed/M6fsky8mlis")
    %div(class="col-sm-6" id="vid_intro")
      %h2 Apocalypse
      %p Apocalypse (En Sabah Nur) is thousands of years old and enemy of the X-Men. Believed to be the first mutant, Apocalypse is cybernetically enhanced by celestial technology.
      = link_to 'Quiz', '', class: 'btn btn-primary btn-lg'
      = link_to 'Follow', '', class: 'btn btn-primary btn-lg'

%section.biography
  .col-sm-8
    %h2 Origin
    %hr
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quod nemo, magnam nulla necessitatibus vitae fuga totam atque perspiciatis exercitationem sed ea eius libero pariatur eum temporibus ipsum illo corrupti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam sapiente nobis aperiam a voluptates reiciendis. Praesentium omnis eaque similique fugit aperiam corporis dolor, nostrum ab amet ducimus! Dolor, pariatur dicta? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quod nemo, magnam nulla necessitatibus vitae fuga totam atque perspiciatis exercitationem sed ea eius libero pariatur eum temporibus ipsum illo corrupti. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam sapiente nobis aperiam a voluptates reiciendis. Praesentium omnis eaque similique fugit aperiam corporis dolor, nostrum ab amet ducimus! Dolor, pariatur dicta? Lorem ipsum dolor sit amet, consectetur adipisicing elit. 

  .panel.panel-default.info
    .panel-heading
      %h3.panel-title Information
    .panel-body
      %p Name
      %p Alias
      %p Abilities
      %p Publisher
    

app/views/ui/index.html.haml
%ul
  - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
    - wireframe = File.basename(file, '.html.haml')
    - unless wireframe == 'index' || wireframe.match(/^_/)
      %li= link_to wireframe.titleize, action: wireframe 

app/views/ui/login.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .well
        = bootstrap_form_for "", layout: :horizontal, label_col: "col-md-2", control_col: "col-md-8" do |f|
          %h2.text-center Login
          %br
          %fieldset
            = f.email_field :email, label: "Email", icon: "envelope", placeholder: "Email"
            = f.password_field :password, label: "Password", icon: "lock", placeholder: "Password"
          %fieldset.col-md-offset-2
            = f.submit "Submit", class: "btn btn-success"

app/views/ui/main.html.haml
.jumbotron
  .container
    %h1 Welcome to HeroSpot!
    %p Test your knowledge of comic book heros, super villains, and video game characters.

%section.biography
  .row
    .col-sm-4
      .thumbnail
        %img(src="/tmp/cyborg-superman-small.jpg" alt="Cyborg-Superman")
        .caption
          %h3 Cyborg Superman 
          %p Cyborg is genetically identical to Superman. With a robotic body designed using Kryptonian technology and genetics, he has Superman's abilities and can possess any machine.
          = link_to 'Start Quiz', '', class: 'btn btn-primary btn-lg'

    .col-sm-4
      .thumbnail
        %img(src="/tmp/apocalypse-small.jpg" alt="Apocalypse")
        .caption
          %h3 Apocalypse
          %p Apocalypse aka En Sabah Nur is thousands of years old and enemy of the X-Men. Believed to be the first mutant, Apocalypse is cybernetically enhanced by celestial technology.
          = link_to 'Start Quiz', '', class: 'btn btn-primary btn-lg'

    .col-sm-4
      .thumbnail
        %img(src="/tmp/judge-dredd-small.jpg" alt="Judge Dredd")
        .caption
          %h3 Judge Dredd
          %p Street Judge of Mega-City One charged to instantly convict, sentence and execute criminals. Rides "Lawmaster" motorcycle equipped with AI controlled laser cannons.
          = link_to 'Start Quiz', '', class: 'btn btn-primary btn-lg'

app/views/ui/question.html.haml
.progress
  %div(class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%; min-width: 2em;")

.img_container
  %img(src="/tmp/cyborg-superman.jpg" alt="Cyborg-Superman" class="img-rounded")

.container
  .row
    .col-md-8.col-md-offset-2
      .well
        = bootstrap_form_for "", layout: :horizontal, label_col: "col-md-2", control_col: "col-md-8" do |f|
          = content_tag(:h2, "What is Cyborg Superman's real name?", class: "text-center")
          %br
          %fieldset
            = f.form_group :answer do 
              = f.radio_button :answer, 0, label: "Clark Kent", checked: true
              = f.radio_button :answer, 1, label: "Hank Henshaw"
              = f.radio_button :answer, 2, label: "Lex Luthor"
              = f.radio_button :answer, 3, label: "John Henry Irons"
          %fieldset.col-md-offset-2
            = f.primary "Answer"

app/views/ui/register.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .well
        = bootstrap_form_for '', layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-8' do |f|
          %h2.text-center Join Us
          %br
          %fieldset
            = f.text_field :full_name, label: 'Full Name', icon: 'user', placeholder: 'Full Name'
            = f.email_field :email, label: 'Email', icon: 'envelope', placeholder: 'Email'
            = f.password_field :password, label: 'Password', icon: 'lock', placeholder: 'Password'
          %fieldset.col-md-offset-2
            = f.submit 'Submit', class: 'btn btn-success'

app/views/users/favs.html.haml
.col-sm-8
  %h2= "You're following ..." 
  %hr
  = render "shared/list_heros", heros: @favs

app/views/users/new.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .well
        = bootstrap_form_for @user, url: join_path, layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-8' do |f|
          %h2.text-center Join Us
          %br
          %fieldset
            = f.text_field :full_name, label: 'Full Name', icon: 'user', placeholder: 'Full Name'
            = f.email_field :email, label: 'Email', icon: 'envelope', placeholder: 'Email'
            = f.password_field :password, label: 'Password', icon: 'lock', placeholder: 'Password'
          %fieldset.col-md-offset-2
            = f.submit 'Submit', class: 'btn btn-success'